<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-11T18:51:26 IST" name="Default suite" finished-at="2023-12-11T18:51:37 IST" duration-ms="10924">
    <groups>
    </groups>
    <test started-at="2023-12-11T18:51:26 IST" name="Default test" finished-at="2023-12-11T18:51:37 IST" duration-ms="10924">
      <class name="Testproj.MainTestcases.Testcases">
        <test-method is-config="true" signature="urlLoading()[pri:0, instance:Testproj.MainTestcases.Testcases@60bd273d]" started-at="2023-12-11T18:51:26 IST" name="urlLoading" finished-at="2023-12-11T18:51:34 IST" duration-ms="8115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- urlLoading -->
        <test-method signature="runTest()[pri:0, instance:Testproj.MainTestcases.Testcases@60bd273d]" started-at="2023-12-11T18:51:34 IST" name="runTest" finished-at="2023-12-11T18:51:37 IST" duration-ms="2713" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[]: Expected 2 values but got 5]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: []: Expected 2 values but got 5
at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:417)
at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:394)
at Testproj.MainTestcases.Testcases.runTest(Testcases.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runTest -->
      </class> <!-- Testproj.MainTestcases.Testcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
